/*
  Builds content/briefs.js from projects/*.md, so the week pages and the
  markdown files in the repo always say the same thing.

  Edit the markdown in projects/, then run:  node scripts/build-briefs.js
  content/briefs.js is generated. Don't edit it by hand.
*/
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const dir = path.join(root, "projects");
const out = path.join(root, "content", "briefs.js");

function buildText() {
  const briefs = {};
  fs.readdirSync(dir)
    .filter((f) => /^W\d{2}-.*\.md$/.test(f))
    .sort()
    .forEach((f) => {
      briefs[f.slice(0, 3)] = {
        file: "projects/" + f,
        text: fs.readFileSync(path.join(dir, f), "utf8").trimEnd() + "\n"
      };
    });
  return (
    "/* GENERATED by scripts/build-briefs.js from projects/*.md. Don't edit by hand. */\n" +
    "window.LT = window.LT || {};\n" +
    "window.LT.briefs = " + JSON.stringify(briefs, null, 2) + ";\n"
  );
}

module.exports = { buildText, out };

if (require.main === module) {
  fs.writeFileSync(out, buildText());
  console.log("Wrote " + path.relative(root, out) + " from projects/.");
}
